import React, { createContext, useContext, useState, useEffect } from 'react';

// Translation strings
const translations = {
  'English': {
    // Navigation
    home: 'Home',
    explore: 'Cafes',
    matches: 'Matches',
    chat: 'Chat',
    nearby: 'Nearby',
    events: 'Events',
    
    // Settings
    settings: 'Settings',
    account: 'Account',
    phoneNumber: 'Phone number',
    email: 'Email',
    connectedAccounts: 'Connected accounts',
    profileVisibility: 'Profile & Visibility',
    visibilityMode: 'Visibility Mode',
    whenYouArePresent: "When you're present to others",
    alwaysVisible: 'Always visible',
    selectedTimes: 'Selected times',
    selectedPlaces: 'Selected places',
    paused: 'Paused',
    locationBasedVisibility: 'Location-based visibility',
    areasToHideOrShow: 'Areas to hide or show yourself',
    timeBasedVisibility: 'Time-based visibility',
    setActiveHours: 'Set active hours',
    contactsVisibility: 'Contacts visibility',
    hideFromContacts: 'Hide from specific contacts',
    notifications: 'Notifications',
    notificationSettings: 'Notification settings',
    matchNotifications: 'Match notifications',
    messageNotifications: 'Message notifications',
    quietHours: 'Quiet hours',
    noNotificationsDuringSetTimes: 'No notifications during set times',
    smartNotifications: 'Smart notifications',
    pulseLearns: 'Pulse learns the best time to reach you',
    matchingPreferences: 'Matching Preferences',
    ageRange: 'Age range',
    safetyTrust: 'Safety & Trust',
    blockedUsers: 'Blocked users',
    reportProblem: 'Report a problem',
    privacyData: 'Privacy & Data',
    profileVisibilityControl: 'Profile visibility',
    controlWhatsShown: "Control what's shown on your profile",
    downloadMyData: 'Download my data',
    privacyPreferences: 'Privacy preferences',
    appPreferences: 'App Preferences',
    language: 'Language',
    unitsOfMeasurement: 'Units of measurement',
    accessibility: 'Accessibility',
    audioTranscription: 'Audio transcription',
    transcribeVoiceMessages: 'Transcribe voice messages',
    subscriptions: 'Subscriptions',
    pulsePremium: 'Pulse Premium',
    unlockAllFeatures: 'Unlock all features',
    inviteGrowth: 'Invite & Growth',
    pulseWorksBest: 'Pulse works best when people you trust are around.',
    sharePulse: 'Share Pulse',
    friendsJoined: 'Friends joined through you',
    peopleWhoSignedUp: 'People who signed up with your invite',
    helpLegal: 'Help & Legal',
    helpCenter: 'Help Center',
    safetyTips: 'Safety Tips',
    communityGuidelines: 'Community Guidelines',
    privacyPolicy: 'Privacy Policy',
    termsOfService: 'Terms of Service',
    pauseAccount: 'Pause account',
    hideWithoutLosing: 'Hide without losing connections',
    logOut: 'Log out',
    dangerZone: 'Danger Zone',
    deleteAccount: 'Delete account',
    thisActionIsPermanent: 'This action is permanent',
    
    // Common
    save: 'Save',
    cancel: 'Cancel',
    close: 'Close',
    confirm: 'Confirm',
    back: 'Back',
    next: 'Next',
    done: 'Done',
    search: 'Search',
    loading: 'Loading...',
    
    // Messages
    languageUpdated: 'Language updated',
    profilePaused: "Profile paused - you won't appear in searches",
    visibilityUpdated: "Visibility updated - you're now always visible",
    
    // Additional UI elements
    profile: 'Profile',
    editProfile: 'Edit Profile',
    viewProfile: 'View Profile',
    addPhoto: 'Add Photo',
    sendMessage: 'Send Message',
    like: 'Like',
    dislike: 'Pass',
    superLike: 'Super Like',
    unmatch: 'Unmatch',
    report: 'Report',
    block: 'Block',
    unblock: 'Unblock',
    today: 'Today',
    tomorrow: 'Tomorrow',
    thisWeek: 'This week',
    nextWeek: 'Next week',
    morning: 'Morning',
    afternoon: 'Afternoon',
    evening: 'Evening',
    night: 'Night',
    allDay: 'All Day',
    selectTime: 'Select time',
    selectDate: 'Select date',
    addLocation: 'Add location',
    hiddenAreas: 'Hidden Areas',
    futurePlaces: 'Future Places',
    addFuturePlace: 'Add future place',
    addHiddenArea: 'Add hidden area',
    placeName: 'Place name',
    chooseIcon: 'Choose an icon',
    whenWillYouBeThere: 'When will you be there?',
    timeOfDay: 'Time of day',
    recurring: 'Recurring',
    weekends: 'Weekends',
    radius: 'Radius',
    meters: 'meters',
    schedule: 'Schedule',
    always: 'Always',
    weekdays: 'Weekdays',
    custom: 'Custom',
    locationSelected: 'Location selected',
    tapMapToSelect: 'Tap on the map to select a location',
    searchLocation: 'Search for a location...',
    noResults: 'No results found',
    connected: 'Connected',
    notConnected: 'Not connected',
    connect: 'Connect',
    disconnect: 'Disconnect',
    verified: 'Verified',
    linkYourAccounts: 'Link your accounts',
    connectSocialAccounts: 'Connect social accounts for easier login and to help verify your profile.',
    yourContacts: 'Your contacts',
    hideAll: 'Hide all',
    showAll: 'Show all',
    totalContacts: 'Total contacts',
    hiddenFrom: 'Hidden from',
    whatsappGroups: 'WhatsApp Groups',
    importWhatsappGroup: 'Import WhatsApp Group',
    membersHidden: 'members hidden',
    noGroupsImported: 'No WhatsApp groups imported yet',
    importGroupToHide: 'Import a group to hide your profile from all members',
    textSize: 'Text Size',
    boldText: 'Bold Text',
    highContrast: 'High Contrast',
    darkMode: 'Dark Mode',
    reduceMotion: 'Reduce Motion',
    largerTouchTargets: 'Larger Touch Targets',
    hapticFeedback: 'Haptic Feedback',
    screenReaderOptimized: 'Screen Reader Optimized',
    showCaptions: 'Show Captions',
    autoPlayVideos: 'Auto-play Videos',
    resetToDefaults: 'Reset to Defaults',
    vision: 'Vision',
    motionInteraction: 'Motion & Interaction',
    audioMedia: 'Audio & Media',
    newMatch: 'New Match',
    newMessage: 'New Message',
    welcome: 'Welcome',
    getStarted: 'Get Started',
    continueWith: 'Continue with',
    or: 'or',
    alreadyHaveAccount: 'Already have an account?',
    dontHaveAccount: "Don't have an account?",
    signIn: 'Sign In',
    signUp: 'Sign Up',
    forgotPassword: 'Forgot Password?',
    resetPassword: 'Reset Password',
    verifyPhone: 'Verify Phone',
    enterCode: 'Enter Code',
    resendCode: 'Resend Code',
    yearsOld: 'years old',
    distance: 'Distance',
    away: 'away',
    online: 'Online',
    lastSeen: 'Last seen',
    typing: 'Typing...',
    sendAMessage: 'Send a message...',
    noMessagesYet: 'No messages yet',
    startConversation: 'Start a conversation!',
    noMatchesYet: 'No matches yet',
    keepSwiping: 'Keep swiping to find your match!',
    
    // Matches Screen
    mutualMatches: 'MUTUAL MATCHES',
    interestedInYou: 'INTERESTED IN YOU',
    filters: 'Filters',
    sortBy: 'Sort By',
    mostRecent: 'Most Recent',
    compatibility: 'Compatibility',
    maxDistance: 'Max Distance (km)',
    activeChatsOnly: 'Active chats only',
    reset: 'Reset',
    apply: 'Apply',
    goToNearby: 'Go to Nearby',
    yourNextConnection: 'Your next connection might be closer than you think.',
    someoneLikedYou: 'Someone liked you',
    keepExploring: 'Someone liked you. Keep exploring to unlock matches.',
    unlock: 'Unlock',
    pass: 'Pass',
    reportUser: 'Report user',
    tellUsWhatHappened: 'Tell us what happened (optional). You can submit without a note.',
    writeNote: 'Write a note (optional)…',
    submitReport: 'Submit report',
    hasBeenBlocked: 'has been blocked.',
    reportSubmitted: 'Report submitted',
    withNote: 'with note',
    sentToReview: 'Profile sent to admin review queue.',
    aboutMe: 'About me',
    lookingFor: 'Looking for',
    km: 'km',
    
    // Chat Screen
    chats: 'Chats',
    messages: 'Messages',
    allChats: 'All Chats',
    unread: 'Unread',
    archived: 'Archived',
    noChatsYet: 'No chats yet',
    startMatching: 'Start matching to begin conversations!',
    typeMessage: 'Type a message...',
    
    // Nearby Screen
    pulse: 'Pulse',
    scanNearby: 'Scan Nearby',
    peopleNearby: 'people nearby',
    viewNearbyPeople: 'View nearby people',
    scanning: 'Scanning...',
    locationRequired: 'Location Required',
    enableLocation: 'Enable Location',
    
    // Explore Screen
    explore: 'Explore',
    allPlaces: 'All',
    bars: 'Bars',
    cafes: 'Cafes',
    liveMusic: 'Live Music',
    nature: 'Nature & Parks',
    workshops: 'Workshops',
    chill: 'Chill',
    nearMe: 'Near me',
    
    // Connected Accounts
    disconnect: 'Disconnect',
    connect: 'Connect',
    
    // Common Actions
    close: 'Close',
    newMatch: 'New connections',
    
    // UserCard
    like: 'Like',
    pass: 'Pass',
    swipeLeftPass: 'Swipe left – Pass',
    swipeRightLike: 'Swipe right – Like',
    passLikeHint: '← Pass · Like →',
    noMoreProfiles: 'No more profiles right now',
    checkBackLater: 'Check back later for new matches',
    lookingForConnections: 'Looking for genuine connections',
    
    // Additional Settings
    notSet: 'Not set',
    notificationsSubtitle: 'Matches, messages, quiet hours, lock-screen',
    ageRangeHelp: 'This helps us suggest more relevant connections.',
    logOutQuestion: 'Log out?',
    logOutConfirmation: 'Are you sure you want to log out of your account?',
    deleteAccountWarning: 'This action is permanent and cannot be undone. All your data will be deleted.',
    profilePausedInfo: 'Your profile is paused. Existing matches & chats still work.',
    audioTranscriptionEnabled: 'Audio transcription enabled',
    audioTranscriptionDisabled: 'Audio transcription disabled',
    googleApple: 'Google, Apple',
    
    // Account Screen
    emailConnectedAccounts: 'Email, connected accounts',
    emailAddress: 'Email address',
    noEmailAdded: 'No email address added',
    notVerified: 'Not verified',
    verified: 'Verified',
    noAccountsConnected: 'No accounts connected',
    accountConnected: 'account connected',
    accountsConnected: 'accounts connected',
    connected: 'Connected',
    connectedAccounts: 'Connected Accounts',
    notConnected: 'Not connected',
    accountSecurityInfo: 'Keep at least one sign-in method active to ensure you can always access your account.',
    
    // Email Edit Screen
    yourEmailAddress: 'Your email address',
    enterEmail: 'Enter your email address',
    sendVerificationCode: 'Send verification code',
    sending: 'Sending...',
    verificationCode: 'Verification code',
    enterCodeSentTo: 'Enter the code we sent to',
    verify: 'Verify',
    verifying: 'Verifying...',
    resendCode: 'Resend code',
    resendCodeIn: 'Resend code in',
    newCodeSent: 'New verification code sent',
    verificationCodeSent: 'Verification code sent to your email',
    emailVerifiedSuccess: 'Email address verified successfully',
    emailVerified: 'Your email address is verified',
    emailPendingVerification: 'Your email is pending verification',
    emailVerificationInfo: 'A verified email address helps secure your account and allows you to recover access if needed.',
    invalidEmail: 'Please enter a valid email address',
    enterVerificationCode: 'Please enter the verification code',
    failedToSendCode: 'Failed to send verification code. Please try again.',
    codeExpired: 'This code has expired. Please request a new one.',
    codeIncorrect: 'The verification code is incorrect',
    emailMismatch: 'This code does not match the pending email.',
    verificationFailed: 'Verification failed. Please try again.',
    
    // Connected Accounts Screen
    disconnectAccount: 'Disconnect account',
    disconnectAccountWarning: 'Disconnecting this account will prevent you from signing in with it in the future.',
    disconnectBlocked: 'To disconnect this account, please set up another sign-in method first (email or another connected account).',
    cannotDisconnectLastMethod: 'To disconnect this account, please set up another sign-in method first (email or another connected account).',
    accountDisconnected: 'Account disconnected',
    accountConnectedSuccess: 'Account connected successfully',
    alreadyConnected: 'This provider is already connected',
    
    // Points Hub
    yourPoints: 'Your Points',
    points: 'Points',
    pts: 'pts',
    minutes: 'min',
    activeNow: 'Active Now',
    spendPoints: 'Spend Points',
    buyPoints: 'Buy Points',
    activate: 'Activate',
    active: 'Active',
    featureUndo: 'Undo',
    featureLikesYou: 'See Who Likes You',
    featureNearbyPriority: 'Nearby Priority',
    featureBeatPulse: 'BeatPulse Boost',
    needMorePoints: 'Need more points',
    activationFailed: 'Activation failed. Please try again.',
    purchaseFailed: 'Purchase failed. Please try again.',
    premiumUnlocksEverything: 'Premium unlocks everything — anytime',
    subscriptionActivePointsDisabled: 'You have an active subscription. Points features are included.',
    boostFeatures: 'Boost your profile temporarily',
    boostYourProfile: 'Boost your profile',
    usePointsToBoost: 'Use points to boost your visibility',
    viewPointsHub: 'View Points Hub',
    boostWithPoints: 'Boost with',
    unlockFeature: 'Unlock',
    usePointsToUnlock: 'Use points to unlock this feature temporarily',
    activateNow: 'Activate Now',
    notEnoughPoints: 'Not enough points',
    getMorePoints: 'Get More Points',
    
    // Chat Gates
    matchFirst: 'Match first',
    canMessageAfterMatch: 'You can message after you match',
    premiumRequired: 'Premium required',
    messagingUnlockedWithPremium: 'Messaging is unlocked with Premium',
    viewPremium: 'View Premium',
    unlockMessaging: 'Unlock messaging',
    unlockMinutesWithPoints: 'Unlock 10 minutes of messaging with points',
    usePoints: 'Use Points',
    messagingLocked: 'Messaging locked',
    chatUnavailable: 'Chat unavailable',
    conversationNoLongerAvailable: 'This conversation is no longer available',
    matchToMessage: 'Match to message',
    upgradeToMessage: 'Upgrade to message',
    unlockToMessage: 'Unlock to message',
    typeMessage: 'Type a message...',
    
    // Likes You
    likesYou: 'Likes You',
    seeWhoLikesYou: 'See who likes you',
    unlockFor10Min: 'Unlock for 10 minutes and see everyone',
    unlockWith80Points: 'Unlock with 80 points',
    orGetPremium: 'Or get Premium for unlimited',
    unlockToSee: 'Unlock to see who likes you',
    noLikesYet: 'No likes yet',
    sessionEnded: 'Session ended',
    activeNow: 'Active now',
    itsAMatch: "It's a Match!",
    activationFailed: 'Activation failed',
    
    // Undo
    undo: 'Undo',
    undoLastSwipe: 'Undo last swipe',
    undoFor30Min: 'Undo for 30 minutes',
    unlockWith40Points: 'Unlock with 40 points',
    cantUndoAfterMatch: "Can't undo after a match",
    noActionToUndo: 'No action to undo',
    undoNotActive: 'Undo is not active',
    cardRestored: 'Card restored',
    
    // Nearby Priority
    nearbyPriority: 'Nearby Priority',
    nearbyPriorityDesc: 'Appear higher in Nearby feed',
    nearbyPriorityFor10Min: 'Priority for 10 minutes',
    unlockWith70Points: 'Unlock with 70 points',
    priorityActive: 'Priority active',
    priorityExpired: 'Priority expired',
    
    // BeatPulse
    beatPulse: 'BeatPulse',
    beatPulseBoost: 'BeatPulse Boost',
    beatPulseDesc: 'Boost your visibility in feeds',
    beatPulseFor15Min: 'Boost for 15 minutes',
    boostActive: 'Boost active',
    boostExpired: 'Boost expired',
    
    // Admin
    adminDashboard: 'Admin Dashboard',
    fullAccess: 'Full Access',
    totalUsers: 'Total Users',
    activeToday: 'Active Today',
    newToday: 'New Today',
    pendingReports: 'Pending Reports',
    userManagement: 'User Management',
    reports: 'Reports',
    systemSettings: 'System Settings',
    suspendUser: 'Suspend User',
    banUser: 'Ban User',
    deleteUser: 'Delete User',
    actionLogged: 'Action logged',
    
    // Visibility
    visible: 'Visible',
    hidden: 'Hidden',
    visibleNow: 'Visible now',
    pausedHiddenEverywhere: "Paused — you're hidden everywhere",
    outsideVisibleHours: 'Outside your visible hours',
    notInVisibleArea: "You're not inside a visible area right now",
    unableToDetermineLocation: 'Unable to determine location',
    accountTemporarilySuspended: 'Account temporarily suspended',
    visibleIn: 'Visible in',
    pauseProfile: 'Pause profile',
    pauseProfileDescription: "You won't be visible anywhere while paused",
    timeVisibility: 'Time visibility',
    locationVisibility: 'Location visibility',
    selectDays: 'Select days',
    setTimeRange: 'Set time range',
    from: 'From',
    to: 'To',
    atLeastOneDayRequired: 'At least one day must be enabled',
    endTimeAfterStart: 'End time must be after start time',
    addArea: 'Add area',
    editArea: 'Edit area',
    deleteArea: 'Delete area',
    areaName: 'Area name',
    radius: 'Radius',
    maxAreasReached: 'Maximum areas reached',
    atLeastOneAreaRequired: 'At least one area must be enabled',
    
    // Data Download
    downloadMyDataSubtitle: 'Get a copy of your personal data',
    downloadYourData: 'Download Your Data',
    downloadDataDescription: 'Request a copy of all your personal data in compliance with GDPR regulations. This export includes everything we have stored about you.',
    includedData: 'What\'s included',
    profileInfo: 'Profile Information',
    profileInfoDesc: 'Name, photos, bio, preferences',
    matchesLikes: 'Matches & Likes',
    matchesLikesDesc: 'Your match history and interactions',
    messagesChats: 'Messages & Chats',
    messagesChatsDesc: 'All your conversations',
    activityLocation: 'Activity & Location',
    activityLocationDesc: 'App usage and location history',
    fileFormat: 'File Format',
    dataRequestTime: 'Your data will be prepared within 24-48 hours. We\'ll send a secure download link to your email.',
    requestMyData: 'Request My Data',
    dataRequestSubmitted: 'Data request submitted! Check your email within 48 hours.',
  },
  
  'עברית': {
    // Navigation
    home: 'בית',
    explore: 'בתי קפה',
    matches: 'התאמות',
    chat: "צ'אט",
    nearby: 'בקרבת מקום',
    events: 'אירועים',
    
    // Settings
    settings: 'הגדרות',
    account: 'חשבון',
    phoneNumber: 'מספר טלפון',
    email: 'אימייל',
    connectedAccounts: 'חשבונות מקושרים',
    profileVisibility: 'פרופיל ונראות',
    visibilityMode: 'מצב נראות',
    whenYouArePresent: 'מתי אתה נראה לאחרים',
    alwaysVisible: 'תמיד נראה',
    selectedTimes: 'זמנים נבחרים',
    selectedPlaces: 'מקומות נבחרים',
    paused: 'מושהה',
    locationBasedVisibility: 'נראות מבוססת מיקום',
    areasToHideOrShow: 'אזורים להסתיר או להציג את עצמך',
    timeBasedVisibility: 'נראות מבוססת זמן',
    setActiveHours: 'הגדר שעות פעילות',
    contactsVisibility: 'נראות אנשי קשר',
    hideFromContacts: 'הסתר מאנשי קשר ספציפיים',
    notifications: 'התראות',
    notificationSettings: 'הגדרות התראות',
    matchNotifications: 'התראות התאמה',
    messageNotifications: 'התראות הודעות',
    quietHours: 'שעות שקטות',
    noNotificationsDuringSetTimes: 'ללא התראות בזמנים מוגדרים',
    smartNotifications: 'התראות חכמות',
    pulseLearns: 'Pulse לומד את הזמן הטוב ביותר להגיע אליך',
    matchingPreferences: 'העדפות התאמה',
    ageRange: 'טווח גילאים',
    safetyTrust: 'בטיחות ואמון',
    blockedUsers: 'משתמשים חסומים',
    reportProblem: 'דווח על בעיה',
    privacyData: 'פרטיות ונתונים',
    profileVisibilityControl: 'נראות פרופיל',
    controlWhatsShown: 'שלוט במה שמוצג בפרופיל שלך',
    downloadMyData: 'הורד את הנתונים שלי',
    privacyPreferences: 'העדפות פרטיות',
    appPreferences: 'העדפות אפליקציה',
    language: 'שפה',
    unitsOfMeasurement: 'יחידות מידה',
    accessibility: 'נגישות',
    audioTranscription: 'תמלול שמע',
    transcribeVoiceMessages: 'תמלל הודעות קוליות',
    subscriptions: 'מנויים',
    pulsePremium: 'Pulse פרימיום',
    unlockAllFeatures: 'פתח את כל התכונות',
    inviteGrowth: 'הזמן וגדל',
    pulseWorksBest: 'Pulse עובד הכי טוב כשאנשים שאתה סומך עליהם נמצאים בסביבה.',
    sharePulse: 'שתף את Pulse',
    friendsJoined: 'חברים שהצטרפו דרכך',
    peopleWhoSignedUp: 'אנשים שנרשמו עם ההזמנה שלך',
    helpLegal: 'עזרה ומשפטי',
    helpCenter: 'מרכז עזרה',
    safetyTips: 'טיפים לבטיחות',
    communityGuidelines: 'הנחיות קהילה',
    privacyPolicy: 'מדיניות פרטיות',
    termsOfService: 'תנאי שימוש',
    pauseAccount: 'השהה חשבון',
    hideWithoutLosing: 'הסתר מבלי לאבד חיבורים',
    logOut: 'התנתק',
    dangerZone: 'אזור סכנה',
    deleteAccount: 'מחק חשבון',
    thisActionIsPermanent: 'פעולה זו היא קבועה',
    
    // Common
    save: 'שמור',
    cancel: 'ביטול',
    close: 'סגור',
    confirm: 'אשר',
    back: 'חזור',
    next: 'הבא',
    done: 'סיום',
    search: 'חיפוש',
    loading: 'טוען...',
    
    // Messages
    languageUpdated: 'השפה עודכנה',
    profilePaused: 'הפרופיל מושהה - לא תופיע בחיפושים',
    visibilityUpdated: 'הנראות עודכנה - אתה כעת תמיד נראה',
    
    // Additional UI elements
    profile: 'פרופיל',
    editProfile: 'ערוך פרופיל',
    viewProfile: 'צפה בפרופיל',
    addPhoto: 'הוסף תמונה',
    sendMessage: 'שלח הודעה',
    like: 'לייק',
    dislike: 'עבור',
    superLike: 'סופר לייק',
    unmatch: 'בטל התאמה',
    report: 'דווח',
    block: 'חסום',
    unblock: 'בטל חסימה',
    today: 'היום',
    tomorrow: 'מחר',
    thisWeek: 'השבוע',
    nextWeek: 'שבוע הבא',
    morning: 'בוקר',
    afternoon: 'צהריים',
    evening: 'ערב',
    night: 'לילה',
    allDay: 'כל היום',
    selectTime: 'בחר שעה',
    selectDate: 'בחר תאריך',
    addLocation: 'הוסף מיקום',
    hiddenAreas: 'אזורים מוסתרים',
    futurePlaces: 'מקומות עתידיים',
    addFuturePlace: 'הוסף מקום עתידי',
    addHiddenArea: 'הוסף אזור מוסתר',
    placeName: 'שם המקום',
    chooseIcon: 'בחר אייקון',
    whenWillYouBeThere: 'מתי תהיה שם?',
    timeOfDay: 'שעה ביום',
    recurring: 'חוזר',
    weekends: 'סופי שבוע',
    radius: 'רדיוס',
    meters: 'מטרים',
    schedule: 'לוח זמנים',
    always: 'תמיד',
    weekdays: 'ימי חול',
    custom: 'מותאם אישית',
    locationSelected: 'מיקום נבחר',
    tapMapToSelect: 'לחץ על המפה לבחירת מיקום',
    searchLocation: 'חפש מיקום...',
    noResults: 'לא נמצאו תוצאות',
    connected: 'מחובר',
    notConnected: 'לא מחובר',
    connect: 'התחבר',
    disconnect: 'התנתק',
    verified: 'מאומת',
    linkYourAccounts: 'קשר את החשבונות שלך',
    connectSocialAccounts: 'חבר חשבונות חברתיים להתחברות קלה יותר ולאימות הפרופיל שלך.',
    yourContacts: 'אנשי הקשר שלך',
    hideAll: 'הסתר הכל',
    showAll: 'הצג הכל',
    totalContacts: 'סה"כ אנשי קשר',
    hiddenFrom: 'מוסתר מ',
    whatsappGroups: 'קבוצות WhatsApp',
    importWhatsappGroup: 'ייבא קבוצת WhatsApp',
    membersHidden: 'חברים מוסתרים',
    noGroupsImported: 'לא יובאו קבוצות WhatsApp עדיין',
    importGroupToHide: 'ייבא קבוצה להסתרת הפרופיל שלך מכל החברים',
    textSize: 'גודל טקסט',
    boldText: 'טקסט מודגש',
    highContrast: 'ניגודיות גבוהה',
    darkMode: 'מצב חשוך',
    reduceMotion: 'הפחת תנועה',
    largerTouchTargets: 'יעדי מגע גדולים יותר',
    hapticFeedback: 'משוב רטט',
    screenReaderOptimized: 'מותאם לקורא מסך',
    showCaptions: 'הצג כתוביות',
    autoPlayVideos: 'הפעל סרטונים אוטומטית',
    resetToDefaults: 'אפס לברירת מחדל',
    vision: 'ראייה',
    motionInteraction: 'תנועה ואינטראקציה',
    audioMedia: 'אודיו ומדיה',
    newMatch: 'התאמה חדשה',
    newMessage: 'הודעה חדשה',
    welcome: 'ברוכים הבאים',
    getStarted: 'בואו נתחיל',
    continueWith: 'המשך עם',
    or: 'או',
    alreadyHaveAccount: 'כבר יש לך חשבון?',
    dontHaveAccount: 'אין לך חשבון?',
    signIn: 'התחבר',
    signUp: 'הירשם',
    forgotPassword: 'שכחת סיסמה?',
    resetPassword: 'אפס סיסמה',
    verifyPhone: 'אמת טלפון',
    enterCode: 'הזן קוד',
    resendCode: 'שלח קוד שוב',
    yearsOld: 'שנים',
    distance: 'מרחק',
    away: 'משם',
    online: 'מחובר',
    lastSeen: 'נראה לאחרונה',
    typing: 'מקליד...',
    sendAMessage: 'שלח הודעה...',
    noMessagesYet: 'אין הודעות עדיין',
    startConversation: 'התחל שיחה!',
    noMatchesYet: 'אין התאמות עדיין',
    keepSwiping: 'המשך להחליק כדי למצוא את ההתאמה שלך!',
    
    // Matches Screen
    mutualMatches: 'התאמות הדדיות',
    interestedInYou: 'מתעניינים בך',
    filters: 'סינון',
    sortBy: 'מיין לפי',
    mostRecent: 'אחרון',
    compatibility: 'התאמה',
    maxDistance: 'מרחק מקסימלי (ק"מ)',
    activeChatsOnly: 'צ\'אטים פעילים בלבד',
    reset: 'אפס',
    apply: 'החל',
    goToNearby: 'עבור לקרובים',
    yourNextConnection: 'החיבור הבא שלך עשוי להיות קרוב יותר ממה שאתה חושב.',
    someoneLikedYou: 'מישהו עשה לך לייק',
    keepExploring: 'מישהו עשה לך לייק. המשך לחקור כדי לפתוח התאמות.',
    unlock: 'פתח',
    pass: 'דלג',
    reportUser: 'דווח על משתמש',
    tellUsWhatHappened: 'ספר לנו מה קרה (אופציונלי). אפשר לשלוח בלי הערה.',
    writeNote: 'כתוב הערה (אופציונלי)...',
    submitReport: 'שלח דיווח',
    hasBeenBlocked: 'נחסם.',
    reportSubmitted: 'הדיווח נשלח',
    withNote: 'עם הערה',
    sentToReview: 'הפרופיל נשלח לבדיקת מנהל.',
    aboutMe: 'עליי',
    lookingFor: 'מחפש/ת',
    km: 'ק"מ',
    
    // Chat Screen
    chats: 'צ\'אטים',
    messages: 'הודעות',
    allChats: 'כל הצ\'אטים',
    unread: 'לא נקראו',
    archived: 'בארכיון',
    noChatsYet: 'אין צ\'אטים עדיין',
    startMatching: 'התחל להתאים כדי להתחיל שיחות!',
    typeMessage: 'כתוב הודעה...',
    
    // Nearby Screen
    pulse: 'Pulse',
    scanNearby: 'סרוק בקרבת מקום',
    peopleNearby: 'אנשים בקרבת מקום',
    viewNearbyPeople: 'הצג אנשים קרובים',
    scanning: 'סורק...',
    locationRequired: 'נדרש מיקום',
    enableLocation: 'הפעל מיקום',
    
    // Explore Screen
    allPlaces: 'הכל',
    bars: 'ברים',
    cafes: 'בתי קפה',
    liveMusic: 'מוזיקה חיה',
    nature: 'טבע ופארקים',
    workshops: 'סדנאות',
    chill: 'רגוע',
    nearMe: 'קרוב אליי',
    
    // Connected Accounts
    disconnect: 'נתק',
    connect: 'התחבר',
    
    // Common Actions
    close: 'סגור',
    newMatch: 'חיבורים חדשים',
    
    // UserCard
    like: 'לייק',
    pass: 'דלג',
    swipeLeftPass: 'החלק שמאלה – דלג',
    swipeRightLike: 'החלק ימינה – לייק',
    passLikeHint: '← דלג · לייק →',
    noMoreProfiles: 'אין עוד פרופילים כרגע',
    checkBackLater: 'חזור מאוחר יותר להתאמות חדשות',
    lookingForConnections: 'מחפש/ת חיבורים אמיתיים',
    
    // Additional Settings
    notSet: 'לא הוגדר',
    notificationsSubtitle: 'התאמות, הודעות, שעות שקטות, מסך נעילה',
    ageRangeHelp: 'זה עוזר לנו להציע חיבורים רלוונטיים יותר.',
    logOutQuestion: 'להתנתק?',
    logOutConfirmation: 'האם את/ה בטוח/ה שברצונך להתנתק מהחשבון?',
    deleteAccountWarning: 'פעולה זו היא קבועה ולא ניתן לבטלה. כל הנתונים שלך יימחקו.',
    profilePausedInfo: 'הפרופיל שלך מושהה. התאמות וצ\'אטים קיימים עדיין עובדים.',
    audioTranscriptionEnabled: 'תמלול שמע הופעל',
    audioTranscriptionDisabled: 'תמלול שמע הושבת',
    googleApple: 'Google, Apple',
    
    // Account Screen
    emailConnectedAccounts: 'אימייל, חשבונות מחוברים',
    emailAddress: 'כתובת אימייל',
    noEmailAdded: 'לא נוספה כתובת אימייל',
    notVerified: 'לא מאומת',
    noAccountsConnected: 'אין חשבונות מחוברים',
    accountConnected: 'חשבון מחובר',
    accountsConnected: 'חשבונות מחוברים',
    connected: 'מחובר',
    connectedAccounts: 'חשבונות מחוברים',
    notConnected: 'לא מחובר',
    verified: 'מאומת',
    accountSecurityInfo: 'שמור לפחות אמצעי התחברות אחד פעיל כדי להבטיח גישה תמידית לחשבון.',
    
    // Email Edit Screen
    yourEmailAddress: 'כתובת האימייל שלך',
    enterEmail: 'הזן את כתובת האימייל שלך',
    sendVerificationCode: 'שלח קוד אימות',
    sending: 'שולח...',
    verificationCode: 'קוד אימות',
    enterCodeSentTo: 'הזן את הקוד ששלחנו אל',
    verify: 'אמת',
    verifying: 'מאמת...',
    resendCode: 'שלח קוד מחדש',
    resendCodeIn: 'שלח קוד מחדש בעוד',
    newCodeSent: 'קוד אימות חדש נשלח',
    verificationCodeSent: 'קוד אימות נשלח לאימייל שלך',
    emailVerifiedSuccess: 'כתובת האימייל אומתה בהצלחה',
    emailVerified: 'כתובת האימייל שלך מאומתת',
    emailPendingVerification: 'האימייל שלך ממתין לאימות',
    emailVerificationInfo: 'כתובת אימייל מאומתת עוזרת לאבטח את החשבון ומאפשרת שחזור גישה במקרה הצורך.',
    invalidEmail: 'נא להזין כתובת אימייל תקינה',
    enterVerificationCode: 'נא להזין את קוד האימות',
    failedToSendCode: 'שליחת קוד האימות נכשלה. נסה שוב.',
    codeExpired: 'הקוד פג תוקף. נא לבקש קוד חדש.',
    codeIncorrect: 'קוד האימות שגוי',
    emailMismatch: 'הקוד לא תואם לאימייל הממתין לאימות.',
    verificationFailed: 'האימות נכשל. נסה שוב.',
    
    // Connected Accounts Screen
    disconnectAccount: 'נתק חשבון',
    disconnectAccountWarning: 'ניתוק חשבון זה ימנע התחברות איתו בעתיד.',
    disconnectBlocked: 'כדי לנתק חשבון זה, נא להגדיר תחילה אמצעי התחברות נוסף (אימייל או חשבון מחובר אחר).',
    cannotDisconnectLastMethod: 'כדי לנתק חשבון זה, נא להגדיר תחילה אמצעי התחברות נוסף (אימייל או חשבון מחובר אחר).',
    accountDisconnected: 'החשבון נותק',
    accountConnectedSuccess: 'החשבון חובר בהצלחה',
    alreadyConnected: 'ספק זה כבר מחובר',
    
    // Points Hub
    yourPoints: 'הנקודות שלך',
    points: 'נקודות',
    pts: 'נק׳',
    minutes: 'דק׳',
    activeNow: 'פעיל עכשיו',
    spendPoints: 'השתמש בנקודות',
    buyPoints: 'קנה נקודות',
    activate: 'הפעל',
    active: 'פעיל',
    featureUndo: 'בטל',
    featureLikesYou: 'ראה מי אוהב אותך',
    featureNearbyPriority: 'עדיפות בקרבת מקום',
    featureBeatPulse: 'בוסט BeatPulse',
    needMorePoints: 'צריך עוד נקודות',
    activationFailed: 'ההפעלה נכשלה. נסה שוב.',
    purchaseFailed: 'הרכישה נכשלה. נסה שוב.',
    premiumUnlocksEverything: 'פרימיום פותח הכל — בכל זמן',
    subscriptionActivePointsDisabled: 'יש לך מנוי פעיל. תכונות הנקודות כלולות.',
    boostFeatures: 'בוסט זמני לפרופיל שלך',
    boostYourProfile: 'בוסט לפרופיל שלך',
    usePointsToBoost: 'השתמש בנקודות להגברת הנראות',
    viewPointsHub: 'צפה בנקודות',
    boostWithPoints: 'בוסט עם',
    unlockFeature: 'פתח',
    usePointsToUnlock: 'השתמש בנקודות לפתיחת תכונה זו באופן זמני',
    activateNow: 'הפעל עכשיו',
    notEnoughPoints: 'אין מספיק נקודות',
    getMorePoints: 'קבל עוד נקודות',
    
    // Chat Gates
    matchFirst: 'התאימו קודם',
    canMessageAfterMatch: 'תוכלו לשלוח הודעות אחרי שתתאימו',
    premiumRequired: 'נדרש פרימיום',
    messagingUnlockedWithPremium: 'הודעות נפתחות עם פרימיום',
    viewPremium: 'צפה בפרימיום',
    unlockMessaging: 'פתח הודעות',
    unlockMinutesWithPoints: 'פתח 10 דקות של הודעות עם נקודות',
    usePoints: 'השתמש בנקודות',
    messagingLocked: 'הודעות נעולות',
    chatUnavailable: 'צ׳אט לא זמין',
    conversationNoLongerAvailable: 'השיחה הזו אינה זמינה יותר',
    matchToMessage: 'התאימו כדי לשלוח הודעה',
    upgradeToMessage: 'שדרגו כדי לשלוח הודעה',
    unlockToMessage: 'פתחו כדי לשלוח הודעה',
    typeMessage: 'הקלד הודעה...',
    
    // Likes You
    likesYou: 'אוהבים אותך',
    seeWhoLikesYou: 'גלה מי אוהב אותך',
    unlockFor10Min: 'פתח ל-10 דקות וראה את כולם',
    unlockWith80Points: 'פתח עם 80 נקודות',
    orGetPremium: 'או קבל פרימיום ללא הגבלה',
    unlockToSee: 'פתח כדי לראות מי אוהב אותך',
    noLikesYet: 'אין לייקים עדיין',
    sessionEnded: 'הסשן הסתיים',
    activeNow: 'פעיל עכשיו',
    itsAMatch: 'יש התאמה!',
    activationFailed: 'ההפעלה נכשלה',
    
    // Undo
    undo: 'בטל',
    undoLastSwipe: 'בטל החלקה אחרונה',
    undoFor30Min: 'בטל ל-30 דקות',
    unlockWith40Points: 'פתח עם 40 נקודות',
    cantUndoAfterMatch: 'לא ניתן לבטל אחרי התאמה',
    noActionToUndo: 'אין פעולה לביטול',
    undoNotActive: 'ביטול לא פעיל',
    cardRestored: 'הכרטיס שוחזר',
    
    // Nearby Priority
    nearbyPriority: 'עדיפות בקרבת מקום',
    nearbyPriorityDesc: 'הופע גבוה יותר בפיד הקרובים',
    nearbyPriorityFor10Min: 'עדיפות ל-10 דקות',
    unlockWith70Points: 'פתח עם 70 נקודות',
    priorityActive: 'עדיפות פעילה',
    priorityExpired: 'העדיפות פגה',
    
    // BeatPulse
    beatPulse: 'BeatPulse',
    beatPulseBoost: 'דחיפת BeatPulse',
    beatPulseDesc: 'הגבר את הנראות שלך בפידים',
    beatPulseFor15Min: 'דחיפה ל-15 דקות',
    boostActive: 'דחיפה פעילה',
    boostExpired: 'הדחיפה פגה',
    
    // Admin
    adminDashboard: 'לוח בקרה',
    fullAccess: 'גישה מלאה',
    totalUsers: 'סה״כ משתמשים',
    activeToday: 'פעילים היום',
    newToday: 'חדשים היום',
    pendingReports: 'דיווחים ממתינים',
    userManagement: 'ניהול משתמשים',
    reports: 'דיווחים',
    systemSettings: 'הגדרות מערכת',
    suspendUser: 'השעה משתמש',
    banUser: 'חסום משתמש',
    deleteUser: 'מחק משתמש',
    actionLogged: 'הפעולה נרשמה',
    
    // Visibility
    visible: 'נראה',
    hidden: 'מוסתר',
    visibleNow: 'נראה כרגע',
    pausedHiddenEverywhere: 'מושהה — אינך נראה לאף אחד',
    outsideVisibleHours: 'מחוץ לשעות הפעילות שלך',
    notInVisibleArea: 'אינך באזור נראות כרגע',
    unableToDetermineLocation: 'לא ניתן לקבוע מיקום',
    accountTemporarilySuspended: 'החשבון מושהה זמנית',
    visibleIn: 'נראה בעוד',
    pauseProfile: 'השהה פרופיל',
    pauseProfileDescription: 'לא תהיה נראה לאף אחד בזמן ההשהיה',
    timeVisibility: 'נראות לפי זמן',
    locationVisibility: 'נראות לפי מיקום',
    selectDays: 'בחר ימים',
    setTimeRange: 'הגדר טווח שעות',
    from: 'מ',
    to: 'עד',
    atLeastOneDayRequired: 'יש לבחור לפחות יום אחד',
    endTimeAfterStart: 'שעת סיום חייבת להיות אחרי שעת התחלה',
    addArea: 'הוסף אזור',
    editArea: 'ערוך אזור',
    deleteArea: 'מחק אזור',
    areaName: 'שם האזור',
    radius: 'רדיוס',
    maxAreasReached: 'הגעת למקסימום אזורים',
    atLeastOneAreaRequired: 'יש להפעיל לפחות אזור אחד',
    
    // Data Download
    downloadMyDataSubtitle: 'קבל עותק של הנתונים האישיים שלך',
    downloadYourData: 'הורדת הנתונים שלך',
    downloadDataDescription: 'בקש עותק של כל הנתונים האישיים שלך בהתאם לתקנות GDPR. הייצוא כולל את כל מה שאחסנו עליך.',
    includedData: 'מה כלול',
    profileInfo: 'פרטי פרופיל',
    profileInfoDesc: 'שם, תמונות, ביוגרפיה, העדפות',
    matchesLikes: 'התאמות ולייקים',
    matchesLikesDesc: 'היסטוריית ההתאמות והאינטראקציות שלך',
    messagesChats: 'הודעות ושיחות',
    messagesChatsDesc: 'כל השיחות שלך',
    activityLocation: 'פעילות ומיקום',
    activityLocationDesc: 'שימוש באפליקציה והיסטוריית מיקום',
    fileFormat: 'פורמט קובץ',
    dataRequestTime: 'הנתונים שלך יוכנו תוך 24-48 שעות. נשלח קישור הורדה מאובטח לאימייל שלך.',
    requestMyData: 'בקש את הנתונים שלי',
    dataRequestSubmitted: 'בקשת הנתונים נשלחה! בדוק את האימייל שלך תוך 48 שעות.',
  },
  
  'Español': {
    // Navigation
    home: 'Inicio',
    explore: 'Cafés',
    matches: 'Matches',
    chat: 'Chat',
    nearby: 'Cercanos',
    events: 'Eventos',
    
    // Settings
    settings: 'Configuración',
    account: 'Cuenta',
    phoneNumber: 'Número de teléfono',
    email: 'Correo electrónico',
    connectedAccounts: 'Cuentas conectadas',
    profileVisibility: 'Perfil y Visibilidad',
    visibilityMode: 'Modo de Visibilidad',
    whenYouArePresent: 'Cuándo eres visible para otros',
    alwaysVisible: 'Siempre visible',
    selectedTimes: 'Horarios seleccionados',
    selectedPlaces: 'Lugares seleccionados',
    paused: 'Pausado',
    notifications: 'Notificaciones',
    language: 'Idioma',
    helpCenter: 'Centro de Ayuda',
    safetyTips: 'Consejos de Seguridad',
    communityGuidelines: 'Normas de la Comunidad',
    privacyPolicy: 'Política de Privacidad',
    termsOfService: 'Términos de Servicio',
    logOut: 'Cerrar sesión',
    deleteAccount: 'Eliminar cuenta',
    
    // Common
    save: 'Guardar',
    cancel: 'Cancelar',
    close: 'Cerrar',
    loading: 'Cargando...',
    languageUpdated: 'Idioma actualizado',
  },
  
  'Français': {
    // Navigation
    home: 'Accueil',
    explore: 'Cafés',
    matches: 'Matchs',
    chat: 'Chat',
    nearby: 'À proximité',
    events: 'Événements',
    
    // Settings
    settings: 'Paramètres',
    account: 'Compte',
    language: 'Langue',
    notifications: 'Notifications',
    helpCenter: "Centre d'aide",
    privacyPolicy: 'Politique de confidentialité',
    logOut: 'Déconnexion',
    
    // Common
    save: 'Enregistrer',
    cancel: 'Annuler',
    loading: 'Chargement...',
    languageUpdated: 'Langue mise à jour',
  },
  
  'Deutsch': {
    // Navigation
    home: 'Startseite',
    explore: 'Cafés',
    matches: 'Matches',
    chat: 'Chat',
    nearby: 'In der Nähe',
    events: 'Veranstaltungen',
    
    // Settings
    settings: 'Einstellungen',
    account: 'Konto',
    language: 'Sprache',
    notifications: 'Benachrichtigungen',
    helpCenter: 'Hilfezentrum',
    privacyPolicy: 'Datenschutzrichtlinie',
    logOut: 'Abmelden',
    
    // Common
    save: 'Speichern',
    cancel: 'Abbrechen',
    loading: 'Wird geladen...',
    languageUpdated: 'Sprache aktualisiert',
  },
};

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguageState] = useState(() => {
    const saved = localStorage.getItem('pulse_language');
    return saved || 'English';
  });

  const setLanguage = (lang) => {
    setLanguageState(lang);
    localStorage.setItem('pulse_language', lang);
    
    // Set document direction for RTL languages
    if (lang === 'עברית') {
      document.documentElement.dir = 'rtl';
      document.documentElement.lang = 'he';
    } else {
      document.documentElement.dir = 'ltr';
      document.documentElement.lang = lang === 'Español' ? 'es' : lang === 'Français' ? 'fr' : lang === 'Deutsch' ? 'de' : 'en';
    }
  };

  // Apply direction on mount
  useEffect(() => {
    if (language === 'עברית') {
      document.documentElement.dir = 'rtl';
      document.documentElement.lang = 'he';
    }
  }, []);

  // Translation function
  const t = (key) => {
    const langTranslations = translations[language] || translations['English'];
    return langTranslations[key] || translations['English'][key] || key;
  };

  const isRTL = language === 'עברית';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
};

export default LanguageContext;
